name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-latest

    services:
      mailcatcher:
        image: dockage/mailcatcher:0.9.0
        ports:
          - 4456:1025

    strategy:
      fail-fast: true
      matrix:
        php: ['7.4', '8.1', '8.2', '8.3', '8.4']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, intl
          tools: composer:v2
          coverage: none

      - name: Prepare test config files
        run: |
          cp tests/acceptance.conf.php.default tests/acceptance.conf.php
          cp tests/smoke.conf.php.default tests/smoke.conf.php

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/simple-phpunit --verbose
        env:
          SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT: 1
